---
title: "Hands-on Exercise 1"
author: "FANG ZI WEI"
---

# Getting Started

## Install and launching R packages

The code chunk below uses p_load() of pacman package to check if tidyverse packages are installed in the computer. If they are, then they will be launched into R.

```{r}
pacman::p_load(tidyverse)
```

## Importing the data

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

# Plotting a simple bar chart

```{r}

ggplot(data = exam_data,
       aes(x = RACE)) +
  geom_bar()
```

```{r}

ggplot(data = exam_data, aes(x= MATHS)) +
  geom_histogram(bins = 10,
                 boundary = 100,
                 color = "black",
                 fill = "grey")+
  ggtitle("Distribution of Maths scores")
```

```{r}
ggplot(data = exam_data,
       aes(x=RACE)) +
  geom_bar()
```

```{r}
ggplot(data = exam_data,
       aes(x=MATHS)) +
  geom_dotplot(dotsize = 0.5)
```

```{r}
ggplot(data = exam_data,
       aes(x=MATHS)) +
  geom_dotplot(binwidth = 2.5,
               dotsize = 0.5) +
  scale_y_continuous(NULL,
                     breaks = NULL)
```

```{r}
ggplot(data = exam_data,
       aes(x=MATHS)) +
  geom_histogram(bins = 20,
                 color = "black",
                 fill = "light blue")
```

```{r}
ggplot(data = exam_data,
       aes(x=MATHS,
           fill = GENDER)) +
  geom_histogram(bins = 20,
                 color = "grey30")
```

```{r}
ggplot(data=exam_data,
       aes(x=MATHS)) +
  geom_density()
```

```{r}
ggplot(data=exam_data,
       aes(x=MATHS,
           colour = GENDER)) +
  geom_density()
```

```{r}
ggplot(data=exam_data,
       aes(y=MATHS,
           x=GENDER)) +
  geom_boxplot()
```

```{r}
ggplot(data=exam_data,
       aes(y=MATHS,
           x= GENDER)) +
  geom_boxplot(notch = TRUE)
```

```{r}
ggplot(data=exam_data,
       aes(y=MATHS,
           x= GENDER)) +
  geom_violin()
```

```{r}
ggplot(data=exam_data,
       aes(x=MATHS,
           y=ENGLISH)) +
  geom_point()
```

```{r}
ggplot(data=exam_data,
       aes(y=MATHS,
           x= GENDER)) +
  geom_boxplot() +
  geom_point(position = "jitter",
             size = 0.5)
```

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, x= GENDER)) +
  geom_boxplot() +
  stat_summary(geom = "point",       
               fun.y="mean",         
               colour ="red",        
               size=4)               
```

```{r}
ggplot(data=exam_data, 
       aes(y = MATHS, x= GENDER)) +
  geom_boxplot() +
  geom_point(stat="summary",        
             fun.y="mean",           
             colour ="red",          
             size=4)          
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, y=ENGLISH)) +
  geom_point() +
  geom_smooth(size=0.5)
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              size=0.5)
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS)) +
  geom_histogram(bins=20) +
    facet_wrap(~ CLASS)
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS)) +
  geom_histogram(bins=20) +
    facet_grid(~ CLASS)
```

```{r}
ggplot(data=exam_data, 
       aes(x=RACE)) +
  geom_bar()
```

```{r}
ggplot(data=exam_data, 
       aes(x=RACE)) +
  geom_bar() +
  coord_flip()
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, size=0.5)
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              size=0.5) +  
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100))
```

```{r}
ggplot(data=exam_data, 
       aes(x=RACE)) +
  geom_bar() +
  coord_flip() +
  theme_gray()
```

```{r}
ggplot(data=exam_data, 
       aes(x=RACE)) +
  geom_bar() +
  coord_flip() +
  theme_classic()
```

```{r}
ggplot(data=exam_data, 
       aes(x=RACE)) +
  geom_bar() +
  coord_flip() +
  theme_minimal()
```
