---
title: "Hands-on Exercise 2"
author: "FANG ZI WEI"
---

# Getting started

```{r}
pacman::p_load(ggrepel, patchwork, ggthemes, hrbrthemes, tidyverse)
```

## Importing data

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

Beyond ggplot2 Annotation:ggrepel

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              size=0.5) +  
  geom_label(aes(label = ID), 
             hjust = .5, 
             vjust = -.5) +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  ggtitle("English scores versus Maths scores for Primary 3")
```

```{r}
ggplot(data=exam_data, 
       aes(x= MATHS, 
           y=ENGLISH)) +
  geom_point() +
  geom_smooth(method=lm, 
              size=0.5) +  
  geom_label_repel(aes(label = ID), 
             fontface = "bold") +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100)) +
  ggtitle("English scores versus Maths scores for Primary 3")
```

```{r}
ggplot(data = exam_data,
       aes(x=MATHS))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  ggtitle("Distribution of Maths scores")
```

```{r}
ggplot(data = exam_data,
       aes(x=MATHS))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_economist()+
  ggtitle("Distribution of Maths scores")
```

```{r}
ggplot(data = exam_data,
       aes(x=MATHS))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_ipsum()+
  ggtitle("Distribution of Maths scores")
```

```{r}
ggplot(data = exam_data,
       aes(x=MATHS))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_ipsum(axis_text_size = 18,
              base_size = 15,
    grid = "Y")+
  ggtitle("Distribution of Maths scores")
```

```{r}
ggplot(data = exam_data,
       aes(x=MATHS))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of Maths scores")
```

```{r}
ggplot(data = exam_data,
       aes(x=ENGLISH))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of English scores")
```

```{r}
ggplot(data=exam_data,
       aes(x=MATHS,
           y=ENGLISH))+
  geom_point()+
  geom_smooth(method = lm, size = 0.5)+
  coord_cartesian(xlim=c(0,100),
                  ylim = c(0,100))+
  ggtitle("English scores versus Maths scores for Primary 3")
```

```{r}
p1 <- ggplot(data = exam_data,
       aes(x=MATHS))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of Maths scores")

p2 <- ggplot(data = exam_data,
       aes(x=ENGLISH))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of English scores")

p1 + p2

```

```{r}
ggplot(data=exam_data,
       aes(x=MATHS,
           y=ENGLISH))+
  geom_point()+
  geom_smooth(method = lm, size = 0.5)+
  coord_cartesian(xlim=c(0,100),
                  ylim = c(0,100))+
  ggtitle("English scores versus Maths scores for Primary 3")
```

```{r}
p1 <- ggplot(data = exam_data,
       aes(x=MATHS))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of Maths scores")

p2 <- ggplot(data = exam_data,
       aes(x=ENGLISH))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of English scores")

p3 <- ggplot(data=exam_data,
       aes(x=MATHS,
           y=ENGLISH))+
  geom_point()+
  geom_smooth(method = lm, size = 0.5)+
  coord_cartesian(xlim=c(0,100),
                  ylim = c(0,100))+
  ggtitle("English scores versus Maths scores for Primary 3")

(p1 /p2) |p3

```

```{r}
p1 <- ggplot(data = exam_data,
       aes(x=MATHS))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of Maths scores")

p2 <- ggplot(data = exam_data,
       aes(x=ENGLISH))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of English scores")

p3 <- ggplot(data=exam_data,
       aes(x=MATHS,
           y=ENGLISH))+
  geom_point()+
  geom_smooth(method = lm, size = 0.5)+
  coord_cartesian(xlim=c(0,100),
                  ylim = c(0,100))+
  ggtitle("English scores versus Maths scores for Primary 3")

((p1 / p2) | p3) + 
  plot_annotation(tag_levels = 'I')
```

```{r}

p1 <- ggplot(data = exam_data,
       aes(x=ENGLISH))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of English scores")

p2 <- ggplot(data=exam_data,
       aes(x=MATHS,
           y=ENGLISH))+
  geom_point()+
  geom_smooth(method = lm, size = 0.5)+
  coord_cartesian(xlim=c(0,100),
                  ylim = c(0,100))+
  ggtitle("English scores versus Maths scores for Primary 3")

p2 + inset_element(p1,
                   left = 0.02, 
                   bottom = 0.7, 
                   right = 0.5, 
                   top = 1)
```

```{r}
p1 <- ggplot(data = exam_data,
       aes(x=MATHS))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of Maths scores")

p2 <- ggplot(data = exam_data,
       aes(x=ENGLISH))+
  geom_histogram(bins = 20,
                 boundary = 100,
                 fill = "grey90",
                 color = "black")+
  theme_grey()+
  coord_cartesian(xlim=c(0,100)) +
  ggtitle("Distribution of English scores")

p3 <- ggplot(data=exam_data,
       aes(x=MATHS,
           y=ENGLISH))+
  geom_point()+
  geom_smooth(method = lm, size = 0.5)+
  coord_cartesian(xlim=c(0,100),
                  ylim = c(0,100))+
  ggtitle("English scores versus Maths scores for Primary 3")

patchwork <- (p1 /p2) |p3
patchwork & theme_economist()

```
