---
title: "In-class_Ex01"
author: "FANG ZI WEI"
---

Getting started
```{r}
pacman::p_load(tidyverse)
```

Importing data
```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

```{r}
ggplot(data = exam_data,
       aes(y=RACE))+
  geom_bar()+
  theme_minimal()+
  theme(
    panel.background = element_rect(fill = "light blue", color = "light blue", size = 0.5, linetype = "solid"),
    panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "white"), 
    panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "white"))
```

```{r}
ggplot(data = exam_data,
       aes(x = RACE)) +
  geom_bar()
```

```{r}
ggplot(data = exam_data,
       aes(x = reorder(RACE,RACE,
                function(x)-length(x))))+
         geom_bar()+
  geom_text(stat="count",
            aes(label = paste0(..count.., ", ",
            round(..count../sum(..count..)*100, 1), "%")), vjust = -0.5)+
  ylim(0,220)+
  ylab("No. of Pupils")+
  xlab("Race")+
  theme(axis.title.y=element_text(angle = 0))
```

```{r}
exam_data %>%
  mutate(RACE = fct_infreq(RACE)) %>%
  ggplot(aes(x = RACE)) + 
  geom_bar()+
  ylim(0,220) +
  geom_text(stat="count", 
      aes(label=paste0(..count.., ", ", 
      round(..count../sum(..count..)*100,
            1), "%")),
      vjust=-1) +
  xlab("Race") +
  ylab("No. of\nPupils") +
  theme(axis.title.y=element_text(angle = 0))
```

```{r}
ggplot(data=exam_data,
       aes(x=MATHS))+
  geom_histogram(bins=20)
```

```{r}
ggplot(data=exam_data,
       aes(x = MATHS))+
  geom_histogram(fill = "light blue",
                 bins = 20,
                 color = "black")+
  geom_vline(aes(xintercept = mean(MATHS, na.rm = T)),
             color = "red",
             linetype = "dashed",
             size = 1)+
  geom_vline(aes(xintercept = median(MATHS, na.rm = T)),
             color = "dark blue",
             linetype = "dashed",
             size = 1)

```

```{r}
ggplot(data=exam_data, 
       aes(x= ENGLISH)) +
  geom_histogram(bins=20) +
    facet_wrap(~ GENDER)
```

```{r}
data <- exam_data
d_bg <- data[,-3]

ggplot(data=exam_data, 
       aes(x= ENGLISH, fill = GENDER)) +
  geom_histogram(bins=20,
                 color = "black")+
  geom_histogram(data=d_bg, fill = "grey", alpha = .5)+
    facet_wrap(~ GENDER)+
      guides(fill = FALSE)+
  theme_bw()+
  ylim(0,30)
```

```{r}
ggplot(data=exam_data,
       aes(x = MATHS,
           y = ENGLISH))+
  geom_point() +
  coord_cartesian(xlim=c(0,100),
                  ylim=c(0,100))+
  geom_hline(yintercept = 50,
             linetype="dashed",
             color = "grey60",
             size=1)+
  geom_vline(xintercept = 50,
             linetype="dashed",
             color = "grey60",
             size=1)
```